nome:  Construir

em: 
  push: 
    ramos: 
      -  principal


jobs: 
  build: 
    nome:  Construir  e  analisar 
    runs-on:  ubuntu-latest
    
    steps: 
      -  uses:  actions/checkout@v4 
        with: 
          fetch-depth:  0   # Clones superficiais devem ser desabilitados para uma melhor relevância da análise 
      -  uses:  sonarsource/sonarqube-scan-action@master 
        env: 
          SONAR_TOKEN:  ${{  secrets.SONAR_TOKEN  }} 
          SONAR_HOST_URL:  ${{  secrets.SONAR_HOST_URL  }} 
      # Se você deseja falhar seu trabalho quando o Quality Gate estiver vermelho, descomente as 
      # linhas a seguir. Isso normalmente seria usado para falhar uma implantação. 
       - uses: sonarsource/sonarqube-quality-gate-action@master 
      # timeout-minutes: 5 
       env: 
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
